---
title: "Hunters as Citizen Scientists"
categories: []
tags:
  - Hunters
  - Conservation
  - Biodiversity
subtitle: ''
summary: ''
authors: []
lastmod: '2020-09-09T14:55:42+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
projects: []
---

Monitoring biodiversity in Europe is usually very costly and time consuming and often resources from governments are limited. [Our paper](https://www.sciencedirect.com/science/article/pii/S2351989420303632) published in April 2020 highlights the unique and important niche that hunters fill in the monitoring of biodiversity across Europe. There are mainly four aspects that makes the work and engagement of hunters so valuable for management authorities and researchers:

During their hunting activity and the management of their hunting grounds, hunters collect diverse data on biodiversity characteristics such as:

* species populations
* species traits
* genetic composition
* community composition
* etc ...

Since hunting grounds cover most of the European countryside, hunters ensure the collection of data over an adequate and large-scale resolution.

**Hunting data can provide time-series** that cover different seasons or range even over several decades which make these datasets useful for monitoring changes in biodiversity and ecosystems.
Hunters collect characteristics mainly on huntable species and those species that are easy to identify with high precision. Species misidentification or other uncertainties are therefore less of an issue when making usage of hunters’ data.
Through the delivery of biological samples (e.g. jaw bones, wings, tissues) from harvested animals, hunters provide data on demographics and health of animals which would have been otherwise not obtainable.

I think that a key point of our study is that collaborations between hunters and scientists are fruitful and should be considered a standard partnership for biodiversity conservation. A result of this is that many of the game species are among the best studied wildlife species we have in Europe.

In this study, me and my fellow co-authors investigated hunters’ contribution to the monitoring of five broad functional species groups: “*ungulates*”, “*large carnivores*”, “*waterfowl*”, “*other birds*” and “*small game*”. The results indicate that in **32 out of the 36 European counties**, hunter-based monitoring of at least one species group is in place which underlines the important role of hunters in the monitoring process of Europe’s biodiversity. A role that is now acknowledged by the scientific community.

>We think that our review has only revealed the tip of the iceberg because a lot of the monitoring activity conducted by hunters is not readily accessible to scientists. We hope that this study can stimulate a broader engagement between hunters and researchers, bringing benefits to both!

